# Generated by Django 3.2.25 on 2024-07-07 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degerler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debi', models.IntegerField()),
                ('gktsicakligi', models.IntegerField()),
                ('gbnemi', models.IntegerField()),
                ('cktsicakligi', models.IntegerField()),
                ('cbnemi', models.IntegerField()),
                ('kapasite', models.IntegerField()),
                ('etuketimi', models.IntegerField()),
                ('hesaplamatarihi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['hesaplamatarihi'],
            },
        ),
    ]
