# Generated by Django 3.2.25 on 2024-07-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hygrometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DB_Temp', models.IntegerField()),
                ('R_Humidity', models.IntegerField()),
                ('M_Content', models.DecimalField(decimal_places=4, max_digits=10)),
                ('S_Volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('S_Enthalpy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('S_Moisture', models.DecimalField(decimal_places=6, max_digits=10)),
                ('EO_Dryair', models.DecimalField(decimal_places=3, max_digits=10)),
                ('SV_Press', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'ordering': ['DB_Temp'],
            },
        ),
        migrations.RenameField(
            model_name='degerler',
            old_name='cbnemi',
            new_name='Airflow',
        ),
        migrations.RenameField(
            model_name='degerler',
            old_name='cktsicakligi',
            new_name='CB_Nemi',
        ),
        migrations.RenameField(
            model_name='degerler',
            old_name='debi',
            new_name='CKT_Sicakligi',
        ),
        migrations.RenameField(
            model_name='degerler',
            old_name='etuketimi',
            new_name='GB_Nemi',
        ),
        migrations.RenameField(
            model_name='degerler',
            old_name='gbnemi',
            new_name='GKT_Sicakligi',
        ),
        migrations.RemoveField(
            model_name='degerler',
            name='gktsicakligi',
        ),
        migrations.RemoveField(
            model_name='degerler',
            name='kapasite',
        ),
    ]
