# Generated by Django 3.2.25 on 2024-07-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunem', '0002_auto_20240712_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degerler',
            name='Airflow',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='degerler',
            name='CKT_Sicakligi',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='degerler',
            name='GKT_Sicakligi',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
