# Generated by Django 3.2.25 on 2024-07-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunem', '0003_auto_20240712_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hygrometric',
            name='EO_Dryair',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='M_Content',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='SV_Press',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='S_Enthalpy',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='S_Volume',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
