# Generated by Django 3.2.25 on 2024-07-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunem', '0004_auto_20240712_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hygrometric',
            name='DB_Temp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='EO_Dryair',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='M_Content',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='R_Humidity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='SV_Press',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='S_Enthalpy',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='S_Moisture',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='S_Volume',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
