# Generated by Django 3.2.25 on 2024-07-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunem', '0005_auto_20240712_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hygrometric',
            name='EO_Dryair',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='M_Content',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='SV_Press',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='S_Enthalpy',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='S_Moisture',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='S_Volume',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
    ]
