# Generated by Django 3.2.25 on 2025-05-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunem', '0006_auto_20240712_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degerler',
            name='Airflow',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='degerler',
            name='CB_Nemi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='degerler',
            name='CKT_Sicakligi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='degerler',
            name='GB_Nemi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='degerler',
            name='GKT_Sicakligi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
