# Generated by Django 3.2.25 on 2025-05-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunem', '0007_auto_20250523_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hygrometric',
            name='DB_Temp',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hygrometric',
            name='R_Humidity',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
    ]
